include:
  - template: Auto-DevOps.gitlab-ci.yml

image: node:current-alpine

pages:
  stage: production
  script:
    - cd website
    - npm install
    - npm run build:ci
  artifacts:
      paths:
        - public
  only:
    - main
  when: manual
