postgresql:
  enabled: false
  install: false
service:
  enabled: true
  name: web
  type: ClusterIP
  url: https://ridebeep.app/
  externalPort: 3001
  internalPort: 3001
livenessProbe:
  path: "/.well-known/apollo/server-health"
  initialDelaySeconds: 20
  timeoutSeconds: 5
  scheme: "HTTP"
  probeType: "httpGet"
readinessProbe:
  path: "/.well-known/apollo/server-health"
  initialDelaySeconds: 20
  timeoutSeconds: 15
  scheme: "HTTP"
  probeType: "httpGet"
