version: '3.5'

services:
  api:
    image: image
    build:
      context: .gitlab
    working_dir: /usr/src
    ports:
      - "3001:3001"
    volumes:
      - type: bind
        source: ./
        target: /usr/src/
        consistency: cached
    command: yarn dev:api
  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: avocado
      TZ: America/New_York

volumes:
  db-data: