version: '3.5'

services:
  api:
    image: image
    build:
      context: .gitlab
    working_dir: /usr/src
    ports:
      - "3001:3001"
    volumes:
      - type: bind
        source: ./
        target: /usr/src/
        consistency: cached
    command: yarn dev:api
