name: production
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: bnussman/avocado:latest
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://avocado.community
    steps:
      - name: Create kube config
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      - name: Install helm
        run: |
          curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
          mv linux-amd64/helm /usr/local/bin/helm
          helm version
      - uses: actions/checkout@v2
      - name: Lint helm charts
        run: helm lint ./.github/helm/
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: node .github/helm/inject.js
        env:
          secrets: ${{ toJSON(secrets) }}
      - name: Deploy
        run: |
          helm upgrade --install --atomic --timeout 1m api ./.github/helm/ -f ./.github/helm/values.yaml --namespace avocado --create-namespace